name: Sync README.md to index.md

on:
  push:
    branches: [main]
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy README.md to index.md
      run: cp README.md index.md

    - name: Check for changes and commit if needed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.md
        git diff --cached --quiet || (git commit -m "Sync README.md to index.md" && git push)
